name: connection_notifier
description: A Flutter package that notifies when there is no internet
  connection and provides simple tools that help track the internet connection
  status.
version: 2.1.0
homepage: https://github.com/AmrAbdelmagid/connection_notifier

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  internet_connection_checker_plus: ^2.5.2
  rxdart: ^0.28.0

dev_dependencies:
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter

flutter: null
